loglevel: info
bind: 0.0.0.0:8080
default_application: default-app
applications:
  - name: default-app
    address: 0.0.0.0:80
    workers: 4
    response_check: true
    transaction_ttl_ms: 60000
spoa:
  bind: 127.0.0.1:12345
  loglevel: info
  applications:
    - name: default-app
      address: 127.0.0.1:80
      workers: 4
      response_check: true
      transaction_ttl_ms: 60000
waf:
  rules:
    - /rules/owasp_crs/crs-setup.conf.example  # OWASP CRS 核心启用文件
    - /rules/owasp_crs/rules/REQUEST-942-APPLICATION-ATTACK-SQLI.conf  # SQL 注入规则文件
